[ Skip to content ](https://ai.pydantic.dev/api/exceptions/<#pydantic_aiexceptions>)
[ ![logo](https://ai.pydantic.dev/img/logo-white.svg) ](https://ai.pydantic.dev/api/exceptions/<../..> "PydanticAI")
PydanticAI 
pydantic_ai.exceptions 
Type to start searching
[ pydantic/pydantic-ai  ](https://ai.pydantic.dev/api/exceptions/<https:/github.com/pydantic/pydantic-ai> "Go to repository")
[ ![logo](https://ai.pydantic.dev/img/logo-white.svg) ](https://ai.pydantic.dev/api/exceptions/<../..> "PydanticAI") PydanticAI 
[ pydantic/pydantic-ai  ](https://ai.pydantic.dev/api/exceptions/<https:/github.com/pydantic/pydantic-ai> "Go to repository")
  * [ Introduction  ](https://ai.pydantic.dev/api/exceptions/<../..>)
  * [ Installation  ](https://ai.pydantic.dev/api/exceptions/install/>)
  * [ Getting Help  ](https://ai.pydantic.dev/api/exceptions/help/>)
  * [ Contributing  ](https://ai.pydantic.dev/api/exceptions/contributing/>)
  * [ Troubleshooting  ](https://ai.pydantic.dev/api/exceptions/troubleshooting/>)
  * Documentation  Documentation 
    * [ Agents  ](https://ai.pydantic.dev/api/exceptions/agents/>)
    * [ Models  ](https://ai.pydantic.dev/api/exceptions/models/>)
    * [ Dependencies  ](https://ai.pydantic.dev/api/exceptions/dependencies/>)
    * [ Function Tools  ](https://ai.pydantic.dev/api/exceptions/tools/>)
    * [ Results  ](https://ai.pydantic.dev/api/exceptions/results/>)
    * [ Messages and chat history  ](https://ai.pydantic.dev/api/exceptions/message-history/>)
    * [ Testing and Evals  ](https://ai.pydantic.dev/api/exceptions/testing-evals/>)
    * [ Debugging and Monitoring  ](https://ai.pydantic.dev/api/exceptions/logfire/>)
    * [ Multi-agent Applications  ](https://ai.pydantic.dev/api/exceptions/multi-agent-applications/>)
    * [ Graphs  ](https://ai.pydantic.dev/api/exceptions/graph/>)
  * [ Examples  ](https://ai.pydantic.dev/api/exceptions/examples/>)
Examples 
    * [ Pydantic Model  ](https://ai.pydantic.dev/api/exceptions/examples/pydantic-model/>)
    * [ Weather agent  ](https://ai.pydantic.dev/api/exceptions/examples/weather-agent/>)
    * [ Bank support  ](https://ai.pydantic.dev/api/exceptions/examples/bank-support/>)
    * [ SQL Generation  ](https://ai.pydantic.dev/api/exceptions/examples/sql-gen/>)
    * [ Flight booking  ](https://ai.pydantic.dev/api/exceptions/examples/flight-booking/>)
    * [ RAG  ](https://ai.pydantic.dev/api/exceptions/examples/rag/>)
    * [ Stream markdown  ](https://ai.pydantic.dev/api/exceptions/examples/stream-markdown/>)
    * [ Stream whales  ](https://ai.pydantic.dev/api/exceptions/examples/stream-whales/>)
    * [ Chat App with FastAPI  ](https://ai.pydantic.dev/api/exceptions/examples/chat-app/>)
    * [ Question Graph  ](https://ai.pydantic.dev/api/exceptions/examples/question-graph/>)
  * API Reference  API Reference 
    * [ pydantic_ai.agent  ](https://ai.pydantic.dev/api/exceptions/<../agent/>)
    * [ pydantic_ai.tools  ](https://ai.pydantic.dev/api/exceptions/<../tools/>)
    * [ pydantic_ai.result  ](https://ai.pydantic.dev/api/exceptions/<../result/>)
    * [ pydantic_ai.messages  ](https://ai.pydantic.dev/api/exceptions/<../messages/>)
    * pydantic_ai.exceptions  [ pydantic_ai.exceptions  ](https://ai.pydantic.dev/api/exceptions/<./>) Table of contents 
      * [ exceptions  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions>)
      * [ ModelRetry  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry.message>)
      * [ UserError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError.message>)
      * [ AgentRunError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError.message>)
      * [ UsageLimitExceeded  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UsageLimitExceeded>)
      * [ UnexpectedModelBehavior  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.message>)
        * [ body  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.body>)
    * [ pydantic_ai.settings  ](https://ai.pydantic.dev/api/exceptions/<../settings/>)
    * [ pydantic_ai.usage  ](https://ai.pydantic.dev/api/exceptions/<../usage/>)
    * [ pydantic_ai.format_as_xml  ](https://ai.pydantic.dev/api/exceptions/<../format_as_xml/>)
    * [ pydantic_ai.models  ](https://ai.pydantic.dev/api/exceptions/<../models/base/>)
    * [ pydantic_ai.models.openai  ](https://ai.pydantic.dev/api/exceptions/<../models/openai/>)
    * [ pydantic_ai.models.anthropic  ](https://ai.pydantic.dev/api/exceptions/<../models/anthropic/>)
    * [ pydantic_ai.models.cohere  ](https://ai.pydantic.dev/api/exceptions/<../models/cohere/>)
    * [ pydantic_ai.models.gemini  ](https://ai.pydantic.dev/api/exceptions/<../models/gemini/>)
    * [ pydantic_ai.models.vertexai  ](https://ai.pydantic.dev/api/exceptions/<../models/vertexai/>)
    * [ pydantic_ai.models.groq  ](https://ai.pydantic.dev/api/exceptions/<../models/groq/>)
    * [ pydantic_ai.models.mistral  ](https://ai.pydantic.dev/api/exceptions/<../models/mistral/>)
    * [ pydantic_ai.models.test  ](https://ai.pydantic.dev/api/exceptions/<../models/test/>)
    * [ pydantic_ai.models.function  ](https://ai.pydantic.dev/api/exceptions/<../models/function/>)
    * [ pydantic_graph  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/graph/>)
    * [ pydantic_graph.nodes  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/nodes/>)
    * [ pydantic_graph.state  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/state/>)
    * [ pydantic_graph.mermaid  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/mermaid/>)
    * [ pydantic_graph.exceptions  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/exceptions/>)


Table of contents 
  * [ exceptions  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions>)
  * [ ModelRetry  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry.message>)
  * [ UserError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError.message>)
  * [ AgentRunError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError.message>)
  * [ UsageLimitExceeded  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UsageLimitExceeded>)
  * [ UnexpectedModelBehavior  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.message>)
    * [ body  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.body>)


  1. [ Introduction  ](https://ai.pydantic.dev/api/exceptions/<../..>)
  2. [ API Reference  ](https://ai.pydantic.dev/api/exceptions/<../agent/>)


# `pydantic_ai.exceptions`
###  ModelRetry
Bases: `Exception[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/exceptions.html#Exception>)`
Exception raised when a tool function should be retried.
The agent will return the message to the model and ask it to try calling the function/tool again.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
 8
 9
10
11
12
13
14
15
16
17
18
19
```
| ```
class ModelRetry(Exception):
"""Exception raised when a tool function should be retried.
  The agent will return the message to the model and ask it to try calling the function/tool again.
  """
  message: str
"""The message to return to the model."""
  def __init__(self, message: str):
    self.message = message
    super().__init__(message)

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = message[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry.message> "pydantic_ai.exceptions.ModelRetry.message")

```

The message to return to the model.
###  UserError
Bases: `RuntimeError[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/exceptions.html#RuntimeError>)`
Error caused by a usage mistake by the application developer — You!
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
22
23
24
25
26
27
28
29
30
```
| ```
class UserError(RuntimeError):
"""Error caused by a usage mistake by the application developer — You!"""
  message: str
"""Description of the mistake."""
  def __init__(self, message: str):
    self.message = message
    super().__init__(message)

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = message[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError.message> "pydantic_ai.exceptions.UserError.message")

```

Description of the mistake.
###  AgentRunError
Bases: `RuntimeError[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/exceptions.html#RuntimeError>)`
Base class for errors occurring during an agent run.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
33
34
35
36
37
38
39
40
41
42
43
44
```
| ```
class AgentRunError(RuntimeError):
"""Base class for errors occurring during an agent run."""
  message: str
"""The error message."""
  def __init__(self, message: str):
    self.message = message
    super().__init__(message)
  def __str__(self) -> str:
    return self.message

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = message[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError.message> "pydantic_ai.exceptions.AgentRunError.message")

```

The error message.
###  UsageLimitExceeded
Bases: `AgentRunError[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError> "pydantic_ai.exceptions.AgentRunError")`
Error raised when a Model's usage exceeds the specified limits.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
47
48
```
| ```
class UsageLimitExceeded(AgentRunError):
"""Error raised when a Model's usage exceeds the specified limits."""

```
  
---|---  
###  UnexpectedModelBehavior
Bases: `AgentRunError[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError> "pydantic_ai.exceptions.AgentRunError")`
Error caused by unexpected Model behavior, e.g. an unexpected response code.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
```
| ```
class UnexpectedModelBehavior(AgentRunError):
"""Error caused by unexpected Model behavior, e.g. an unexpected response code."""
  message: str
"""Description of the unexpected behavior."""
  body: str | None
"""The body of the response, if available."""
  def __init__(self, message: str, body: str | None = None):
    self.message = message
    if body is None:
      self.body: str | None = None
    else:
      try:
        self.body = json.dumps(json.loads(body), indent=2)
      except ValueError:
        self.body = body
    super().__init__(message)
  def __str__(self) -> str:
    if self.body:
      return f'{self.message}, body:\n{self.body}'
    else:
      return self.message

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = message[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.message> "pydantic_ai.exceptions.UnexpectedModelBehavior.message")

```

Description of the unexpected behavior.
####  body `instance-attribute`
```
body: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) | None = dumps[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/json.html#json.dumps> "json.dumps")(loads[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/json.html#json.loads> "json.loads")(body[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.body> "pydantic_ai.exceptions.UnexpectedModelBehavior.body")), indent=2)

```

The body of the response, if available.
© Pydantic Services Inc. 2024 to present 
